import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from src.logger import logger
from src.exception import CustomException

class EDAAutomator:
    def __init__(self, data_path: str):
        self.project_root = Path(__file__).resolve().parent.parent
        self.data = pd.read_csv(data_path)
        self.report_dir = self.project_root / "reports"
        self.report_dir.mkdir(parents=True, exist_ok=True)
        
        # Define features
        self.numerical_features = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
        self.categorical_features = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']

    def generate_class_distribution(self):
        """Generates and saves target class balance plots."""
        try:
            logger.info("Generating Class Distribution plot...")
            fig, axes = plt.subplots(1, 2, figsize=(14, 5))
            class_counts = self.data['target'].value_counts()
            colors = ['#4CAF50', '#F44336']

            # Bar plot
            axes[0].bar(['No Disease (0)', 'Disease (1)'], class_counts.values, color=colors, alpha=0.8)
            axes[0].set_title('Heart Disease Distribution', fontsize=14, fontweight='bold')

            # Pie chart
            axes[1].pie(class_counts.values, labels=['No Disease', 'Disease'], autopct='%1.1f%%', colors=colors, startangle=90)
            
            plt.tight_layout()
            plt.savefig(self.report_dir / "class_distribution.png", dpi=300)
            plt.close()
        except Exception as e:
            raise CustomException(e, sys)

    def generate_correlation_heatmap(self):
        """Generates and saves the correlation heatmap."""
        try:
            logger.info("Generating Correlation Heatmap...")
            plt.figure(figsize=(14, 10))
            corr_matrix = self.data.corr()
            mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
            
            sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f', cmap='coolwarm', square=True)
            plt.title('Feature Correlation Heatmap', fontsize=16, fontweight='bold')
            
            plt.tight_layout()
            plt.savefig(self.report_dir / "correlation_heatmap.png", dpi=300)
            plt.close()
        except Exception as e:
            raise CustomException(e, sys)

    def generate_numerical_distributions(self):
        """Generates histograms for numerical features."""
        try:
            logger.info("Generating Numerical Distribution plots...")
            existing_num = [f for f in self.numerical_features if f in self.data.columns]
            fig, axes = plt.subplots(2, 3, figsize=(16, 10))
            axes = axes.flatten()

            for idx, feature in enumerate(existing_num[:6]):
                sns.histplot(data=self.data, x=feature, kde=True, ax=axes[idx], color='skyblue')
                axes[idx].set_title(f'{feature} Distribution')

            plt.tight_layout()
            plt.savefig(self.report_dir / "numerical_distributions.png", dpi=300)
            plt.close()
        except Exception as e:
            raise CustomException(e, sys)

    def save_stats(self):
        stats = self.data.describe().to_json()
        with open(self.report_dir / "data_profile.json", "w") as f:
            f.write(stats)
        logger.info("Data profile JSON saved for drift monitoring.")
    
    def run_full_report(self):
        logger.info("Starting full automated EDA report generation")
        self.generate_class_distribution()
        self.generate_correlation_heatmap()
        self.generate_numerical_distributions()
        self.save_stats()
        logger.info(f"All EDA plots successfully saved to: {self.report_dir}")

if __name__ == "__main__":
    # Point to the processed data generated by ingestion.py
    processed_data = "data/processed/heart_cleaned.csv"
    if os.path.exists(processed_data):
        eda = EDAAutomator(processed_data)
        eda.run_full_report()
    else:
        print("Processed data not found. Please run ingestion.py first.")